//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesManager.UI.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilesManager.UI.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append:.
        /// </summary>
        public static string Append_Label {
            get {
                return ResourceManager.GetString("Append_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Add a text at the end of the file name.
        /// </summary>
        public static string Append_Tooltip {
            get {
                return ResourceManager.GetString("Append_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENAME FILES.
        /// </summary>
        public static string GeneralHeader {
            get {
                return ResourceManager.GetString("GeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremented number + postfix.
        /// </summary>
        public static string Method_IncrementNumber_Label {
            get {
                return ResourceManager.GetString("Method_IncrementNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE EXAMPLE
        ///
        ///INPUT:
        ///- picture20.png
        ///- file42.jpeg
        ///
        ///PARAMETERS:
        ///- Prefix: &quot;test #&quot;
        ///- Start number: 0
        ///- Postfix: &quot;_file&quot;
        ///
        ///RESULT:
        ///- test #0_file.png
        ///- test #1_file.jpeg.
        /// </summary>
        public static string Method_IncrementNumber_Tooltip {
            get {
                return ResourceManager.GetString("Method_IncrementNumber_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leading zeros.
        /// </summary>
        public static string Method_LeadingZeros_Label {
            get {
                return ResourceManager.GetString("Method_LeadingZeros_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE EXAMPLE
        ///
        ///INPUT:
        ///- 1.jpg
        ///- 15.jpg
        ///
        ///PARAMETERS:
        ///- Set: 2
        ///
        ///RESULT:
        ///- 0001.jpg
        ///- 0015.jpg.
        /// </summary>
        public static string Method_LeadingZeros_Tooltip {
            get {
                return ResourceManager.GetString("Method_LeadingZeros_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepend / append text.
        /// </summary>
        public static string Method_PrependAppend_Label {
            get {
                return ResourceManager.GetString("Method_PrependAppend_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE EXAMPLE
        ///
        ///INPUT:
        ///- Archive.zip
        ///
        ///PARAMETERS:
        ///- Prepend: &quot;My_[&quot;
        ///- Append: &quot;]_2022&quot;
        ///
        ///RESULT:
        ///- My_[Archive]_2022.zip.
        /// </summary>
        public static string Method_PrependAppend_Tooltip {
            get {
                return ResourceManager.GetString("Method_PrependAppend_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix:.
        /// </summary>
        public static string Postfix_Label {
            get {
                return ResourceManager.GetString("Postfix_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Optional text to be added after the number.
        /// </summary>
        public static string Postfix_Tooltip {
            get {
                return ResourceManager.GetString("Postfix_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix:.
        /// </summary>
        public static string Prefix_Label {
            get {
                return ResourceManager.GetString("Prefix_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Optional text to be added before the number.
        /// </summary>
        public static string Prefix_Tooltip {
            get {
                return ResourceManager.GetString("Prefix_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepend:.
        /// </summary>
        public static string Prepend_Label {
            get {
                return ResourceManager.GetString("Prepend_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Add a text at the beginning of the file name.
        /// </summary>
        public static string Prepend_Tooltip {
            get {
                return ResourceManager.GetString("Prepend_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ProcessButton_Content {
            get {
                return ResourceManager.GetString("ProcessButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Starts processing given files based on a selected method.
        /// </summary>
        public static string ProcessButton_Tooltip {
            get {
                return ResourceManager.GetString("ProcessButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Select to activate this method.
        /// </summary>
        public static string RadioButton_Tooltip {
            get {
                return ResourceManager.GetString("RadioButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton_Content {
            get {
                return ResourceManager.GetString("ResetButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Clears loaded files and all values from methods.
        /// </summary>
        public static string ResetButton_Tooltip {
            get {
                return ResourceManager.GetString("ResetButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set:.
        /// </summary>
        public static string Set_Label {
            get {
                return ResourceManager.GetString("Set_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Set the amount of leading zeros before the file name.
        /// </summary>
        public static string Set_Tooltip {
            get {
                return ResourceManager.GetString("Set_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start number:.
        /// </summary>
        public static string StartNumber_Label {
            get {
                return ResourceManager.GetString("StartNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: Rename given files using an incremented start number.
        /// </summary>
        public static string StartNumber_Tooltip {
            get {
                return ResourceManager.GetString("StartNumber_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIP: Empty or only whitespaces content will be ignored
        ///
        ///Invalid characters:  \ / : * ? &quot; &lt; &gt; |.
        /// </summary>
        public static string Tip_NonEmptyFieldContent_Tooltip {
            get {
                return ResourceManager.GetString("Tip_NonEmptyFieldContent_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIP: Only positive numbers from the range [0 - 65 535].
        /// </summary>
        public static string Tip_OnlyPositiveNumbers_Tooltip {
            get {
                return ResourceManager.GetString("Tip_OnlyPositiveNumbers_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIP: Only positive numbers from the range [0 - 7].
        /// </summary>
        public static string Tip_OnlyVerySmallPositiveNumbers_Tooltip {
            get {
                return ResourceManager.GetString("Tip_OnlyVerySmallPositiveNumbers_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager (v0.3.1-alpha).
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
